#ifndef LOGGER_H
#define LOGGER_H

#include <QString>
#include <QStringList>

/**
 * Logger - the application's own log file.
 *
 * Everything that goes through qDebug()/qWarning()/qCritical()/qFatal() as well
 * as the engine's stdout/stderr ends up in
 * `<AppLocalData>/logs/fetchora-<date>.log`, one file per day, and the file is
 * flushed line by line: when the app disappears (a crash is exactly the case
 * this exists for) the last line before it is on disk, not in a buffer.
 *
 * Housekeeping is automatic and runs at startup and once a day afterwards:
 *
 *   * a file that grows past kMaxFileBytes is rotated to
 *     `fetchora-<date>-<time>.log` so one noisy day cannot fill the disk,
 *   * files older than `retentionDays()` are deleted,
 *   * and the directory is trimmed to kMaxTotalBytes, oldest first.
 *
 * The crash path is deliberately dependency-free: the exception filter writes
 * the failure, the last few log lines and a backtrace of return addresses, then
 * asks DbgHelp for a minidump next to the log. `Fetchora.map` (generated by
 * CMake for MinGW builds) turns those addresses back into function names.
 *
 * A plain namespace rather than a QObject: there is one log, callers should not
 * have to find it first, and nothing here is worth emitting a signal for.
 */
namespace Logger {

/// Install the message handler, write the startup banner and prune old files.
/// Safe to call more than once; needs QCoreApplication's name to be set already.
void install();

/// Directory holding the log files; created on demand.
QString directory();
/// The file currently being appended to.
QString currentFile();

/// Delete files outside the retention window / size budget. Returns how many
/// were removed. Called by install() and once a day afterwards.
int prune();

/// Append one line to the log (and to stderr when the level is a warning).
/// `channel` is a short tag such as "engine" or "rpc".
void line(const QString &channel, const QString &text, bool isError = false);

/// The last `maxLines` lines written, oldest first. Used by the crash handler
/// and by the settings page's "save log" action.
QStringList recent(int maxLines = 200);

int retentionDays();
void setRetentionDays(int days);

} // namespace Logger

#endif // LOGGER_H
